import { computed, ref } from "vue";
import type { Language } from "element-plus/es/locale";
import de from "element-plus/es/locale/lang/de";
import en from "element-plus/es/locale/lang/en";
import fr from "element-plus/es/locale/lang/fr";
import ja from "element-plus/es/locale/lang/ja";
import ko from "element-plus/es/locale/lang/ko";
import zhCn from "element-plus/es/locale/lang/zh-cn";
import zhTw from "element-plus/es/locale/lang/zh-tw";
import { extraExactTextTranslations } from "./appExtraTranslations";

export type AppLocale = "en" | "zh-CN" | "zh-TW" | "ja" | "ko" | "fr" | "de";

type MessageTree = {
  [key: string]: string | MessageTree;
};

const LOCALE_STORAGE_KEY = "bscc.app.locale";

const elementPlusLocales: Record<AppLocale, Language> = {
  en,
  "zh-CN": zhCn,
  "zh-TW": zhTw,
  ja,
  ko,
  fr,
  de
};

const localeOptions = [
  { value: "en", label: "English" },
  { value: "zh-CN", label: "简体中文" },
  { value: "zh-TW", label: "繁體中文" },
  { value: "ja", label: "日本語" },
  { value: "ko", label: "한국어" },
  { value: "fr", label: "Français" },
  { value: "de", label: "Deutsch" }
] as const satisfies Array<{ value: AppLocale; label: string }>;

const keyMessages: Record<AppLocale, MessageTree> = {
  "zh-CN": {
    app: {
      defaultSiteTitle: "标书查重系统",
      defaultHomeTags: ["无需登陆", "基础免费", "不限页数", "不限大小", "开箱即用"].join("|")
    },
    shell: {
      systemNotice: "系统公告",
      language: "语言",
      version: "版本",
      menu: {
        home: "主页",
        upload: "上传查重",
        free: "免费查重",
        check: "标书检查",
        compliance: "标书合规",
        docs: "文档"
      },
      step: {
        upload: "上传工作台",
        uploadSub: "提交标书文件",
        processing: "AI 查重中",
        processingSub: "智能比对中",
        results: "结果总览",
        resultsSub: "查看查重排行",
        compare: "对比证据",
        compareSub: "原文差异对比"
      },
      email: {
        eyebrow: "客服邮箱",
        desc: "适合发送问题截图、需求说明与联调信息"
      },
      qrFallback: "图片未就绪"
    },
    upload: {
      title: "任务创建工作台",
      subtitle: "上传主标书 A 与对比标书 B 即可快速进行查重比对。",
      recover: "找回历史任务结果",
      keywordLabel: "关键字查重",
      keywordPlaceholder: "输入关键字后按回车添加（示例：围标、独家授权）",
      start: "开始智能查重",
      recoverDialogTitle: "找回查重结果",
      recoverTip: "请输入系统生成的以 T 开头的任务编号",
      recoverPlaceholder: "例如：T20260626xxxx",
      cancel: "取消",
      recoverNow: "立即找回",
      aTitle: "主标书 A",
      aDesc: "建议上传最终提交版本，仅允许 1 份。",
      bTitle: "对比标书 B",
      bDesc: "支持 1-10 份，超过 1 份按 1 对多流程处理。",
      warnings: {
        missingA: "请先选择主标书 A",
        missingB: "请至少选择 1 份 B 标书",
        exceedB: "B 标书最多选择 10 份",
        unsupported: "{name} 暂不支持，请上传 DOCX 或可复制文本 PDF",
        createFailed: "创建任务失败"
      }
    },
    uploadCard: {
      clear: "清空",
      importPrimary: "导入主文档",
      importBatch: "批量导入对比文件",
      replaceHint: "可继续拖入替换，系统不会自动上传。",
      dropHint: "拖拽文件到此处，或点击选择文件。",
      empty: "尚未选择文件",
      selectedSingle: "{name}",
      selectedMulti: "已选择 {count} 份文件"
    },
    seo: {
      keyPoints: "Key Points",
      insight: "Insight",
      workflow: "Workflow",
      faq: "FAQ",
      related: "Related",
      viewPage: "查看页面"
    },
    stepper: {
      progress: "进度"
    }
  },
  en: {
    app: {
      defaultSiteTitle: "Bid Similarity Check",
      defaultHomeTags: ["No Login", "Free Preview", "Unlimited Pages", "Unlimited Size", "Ready to Use"].join("|")
    },
    shell: {
      systemNotice: "System Notice",
      language: "Language",
      version: "Version",
      menu: {
        home: "Home",
        upload: "Upload",
        free: "Free Check",
        check: "Bid Review",
        compliance: "Compliance",
        docs: "Docs"
      },
      step: {
        upload: "Upload Desk",
        uploadSub: "Submit bid files",
        processing: "AI Checking",
        processingSub: "Running comparison",
        results: "Results",
        resultsSub: "Review ranking",
        compare: "Evidence",
        compareSub: "Compare originals"
      },
      email: {
        eyebrow: "Support Email",
        desc: "Best for sending screenshots, issue details and integration notes"
      },
      qrFallback: "Image unavailable"
    },
    upload: {
      title: "Task Workspace",
      subtitle: "Upload master bid A and comparison bid B to start similarity analysis.",
      recover: "Recover previous task",
      keywordLabel: "Keyword Check",
      keywordPlaceholder: "Type a keyword and press Enter to add it (example: collusion, exclusive authorization)",
      start: "Start AI Check",
      recoverDialogTitle: "Recover Check Result",
      recoverTip: "Enter the task ID generated by the system, starting with T",
      recoverPlaceholder: "Example: T20260626xxxx",
      cancel: "Cancel",
      recoverNow: "Recover Now",
      aTitle: "Master Bid A",
      aDesc: "Upload the final submission version. Only one file is allowed.",
      bTitle: "Comparison Bid B",
      bDesc: "Supports 1 to 10 files. More than one file follows a one-to-many workflow.",
      warnings: {
        missingA: "Please select master bid A first.",
        missingB: "Please select at least one comparison bid B.",
        exceedB: "You can upload up to 10 B files.",
        unsupported: "{name} is not supported. Please upload a DOCX file or a selectable-text PDF.",
        createFailed: "Failed to create task."
      }
    },
    uploadCard: {
      clear: "Clear",
      importPrimary: "Import main file",
      importBatch: "Import comparison files",
      replaceHint: "You can drag more files here to replace them. Nothing is uploaded automatically.",
      dropHint: "Drag files here, or click to select files.",
      empty: "No file selected yet",
      selectedSingle: "{name}",
      selectedMulti: "{count} files selected"
    },
    seo: {
      keyPoints: "Key Points",
      insight: "Insight",
      workflow: "Workflow",
      faq: "FAQ",
      related: "Related",
      viewPage: "View page"
    },
    stepper: {
      progress: "Progress"
    }
  },
  "zh-TW": {
    app: {
      defaultSiteTitle: "標書查重系統",
      defaultHomeTags: ["無需登入", "基礎免費", "不限頁數", "不限大小", "開箱即用"].join("|")
    },
    shell: {
      systemNotice: "系統公告",
      language: "語言",
      version: "版本",
      menu: {
        home: "主頁",
        upload: "上傳查重",
        free: "免費查重",
        check: "標書檢查",
        compliance: "標書合規",
        docs: "文件"
      },
      step: {
        upload: "上傳工作台",
        uploadSub: "提交標書檔案",
        processing: "AI 查重中",
        processingSub: "智慧比對中",
        results: "結果總覽",
        resultsSub: "查看查重排行",
        compare: "對比證據",
        compareSub: "原文差異對比"
      },
      email: {
        eyebrow: "客服郵箱",
        desc: "適合發送問題截圖、需求說明與聯調資訊"
      },
      qrFallback: "圖片未就緒"
    },
    upload: {
      title: "任務建立工作台",
      subtitle: "上傳主標書 A 與對比標書 B，即可快速進行查重比對。",
      recover: "找回歷史任務結果",
      keywordLabel: "關鍵字查重",
      keywordPlaceholder: "輸入關鍵字後按 Enter 新增（例如：圍標、獨家授權）",
      start: "開始智慧查重",
      recoverDialogTitle: "找回查重結果",
      recoverTip: "請輸入系統產生、以 T 開頭的任務編號",
      recoverPlaceholder: "例如：T20260626xxxx",
      cancel: "取消",
      recoverNow: "立即找回",
      aTitle: "主標書 A",
      aDesc: "建議上傳最終提交版本，僅允許 1 份。",
      bTitle: "對比標書 B",
      bDesc: "支援 1 到 10 份，超過 1 份時按 1 對多流程處理。",
      warnings: {
        missingA: "請先選擇主標書 A",
        missingB: "請至少選擇 1 份 B 標書",
        exceedB: "B 標書最多可選 10 份",
        unsupported: "{name} 暫不支援，請上傳 DOCX 或可複製文字的 PDF",
        createFailed: "建立任務失敗"
      }
    },
    uploadCard: {
      clear: "清空",
      importPrimary: "匯入主文件",
      importBatch: "批量匯入對比文件",
      replaceHint: "可繼續拖入替換，系統不會自動上傳。",
      dropHint: "拖曳檔案到此處，或點擊選擇檔案。",
      empty: "尚未選擇檔案",
      selectedSingle: "{name}",
      selectedMulti: "已選擇 {count} 份檔案"
    },
    seo: {
      keyPoints: "重點",
      insight: "洞察",
      workflow: "流程",
      faq: "常見問題",
      related: "相關頁面",
      viewPage: "查看頁面"
    },
    stepper: {
      progress: "進度"
    }
  },
  ja: {
    app: {
      defaultSiteTitle: "入札書類重複チェック",
      defaultHomeTags: ["ログイン不要", "無料プレビュー", "ページ数無制限", "容量制限なし", "すぐ使える"].join("|")
    },
    shell: {
      systemNotice: "システム通知",
      language: "言語",
      version: "バージョン",
      menu: {
        home: "ホーム",
        upload: "アップロード",
        free: "無料チェック",
        check: "入札レビュー",
        compliance: "コンプライアンス",
        docs: "ドキュメント"
      },
      step: {
        upload: "アップロード",
        uploadSub: "入札書類を送信",
        processing: "AI チェック中",
        processingSub: "比較処理中",
        results: "結果",
        resultsSub: "ランキングを確認",
        compare: "証拠比較",
        compareSub: "原文を比較"
      },
      email: {
        eyebrow: "サポートメール",
        desc: "スクリーンショット、要件説明、連携情報の送信に適しています"
      },
      qrFallback: "画像を表示できません"
    },
    upload: {
      title: "タスク作成ワークスペース",
      subtitle: "元の入札書類 A と比較用入札書類 B をアップロードして重複チェックを開始します。",
      recover: "過去のタスクを復元",
      keywordLabel: "キーワードチェック",
      keywordPlaceholder: "キーワードを入力して Enter で追加します（例：談合、独占許可）",
      start: "AI チェックを開始",
      recoverDialogTitle: "チェック結果を復元",
      recoverTip: "T で始まるタスク ID を入力してください",
      recoverPlaceholder: "例：T20260626xxxx",
      cancel: "キャンセル",
      recoverNow: "今すぐ復元",
      aTitle: "元文書 A",
      aDesc: "最終提出版のアップロードを推奨します。1 ファイルのみ対応します。",
      bTitle: "比較文書 B",
      bDesc: "1 から 10 ファイルまで対応します。複数の場合は 1 対多のワークフローになります。",
      warnings: {
        missingA: "先に元文書 A を選択してください。",
        missingB: "少なくとも 1 件の比較文書 B を選択してください。",
        exceedB: "B 文書は最大 10 件までです。",
        unsupported: "{name} は未対応です。DOCX またはテキスト選択可能な PDF をアップロードしてください。",
        createFailed: "タスクの作成に失敗しました。"
      }
    },
    uploadCard: {
      clear: "クリア",
      importPrimary: "メイン文書を追加",
      importBatch: "比較文書を追加",
      replaceHint: "さらにドラッグして置き換えできます。自動アップロードは行われません。",
      dropHint: "ここにファイルをドラッグするか、クリックして選択してください。",
      empty: "まだファイルが選択されていません",
      selectedSingle: "{name}",
      selectedMulti: "{count} 件のファイルを選択済み"
    },
    seo: {
      keyPoints: "ポイント",
      insight: "インサイト",
      workflow: "ワークフロー",
      faq: "FAQ",
      related: "関連ページ",
      viewPage: "ページを見る"
    },
    stepper: {
      progress: "進行状況"
    }
  },
  ko: {
    app: {
      defaultSiteTitle: "입찰 문서 유사도 검사",
      defaultHomeTags: ["로그인 불필요", "무료 미리보기", "페이지 제한 없음", "용량 제한 없음", "즉시 사용"].join("|")
    },
    shell: {
      systemNotice: "시스템 공지",
      language: "언어",
      version: "버전",
      menu: {
        home: "홈",
        upload: "업로드",
        free: "무료 검사",
        check: "입찰 검토",
        compliance: "준수 점검",
        docs: "문서"
      },
      step: {
        upload: "업로드",
        uploadSub: "입찰 파일 제출",
        processing: "AI 검사 중",
        processingSub: "비교 분석 진행 중",
        results: "결과",
        resultsSub: "순위 확인",
        compare: "증거 비교",
        compareSub: "원문 비교"
      },
      email: {
        eyebrow: "지원 이메일",
        desc: "스크린샷, 요구사항 설명, 연동 정보를 보내기에 적합합니다"
      },
      qrFallback: "이미지를 표시할 수 없습니다"
    },
    upload: {
      title: "작업 생성 워크스페이스",
      subtitle: "원본 입찰서 A와 비교 입찰서 B를 업로드하여 유사도 검사를 시작합니다.",
      recover: "이전 작업 복구",
      keywordLabel: "키워드 검사",
      keywordPlaceholder: "키워드를 입력한 뒤 Enter 로 추가하세요 (예: 담합, 독점 승인)",
      start: "AI 검사 시작",
      recoverDialogTitle: "검사 결과 복구",
      recoverTip: "T 로 시작하는 작업 번호를 입력하세요",
      recoverPlaceholder: "예: T20260626xxxx",
      cancel: "취소",
      recoverNow: "지금 복구",
      aTitle: "원본 문서 A",
      aDesc: "최종 제출본 업로드를 권장합니다. 1개 파일만 허용됩니다.",
      bTitle: "비교 문서 B",
      bDesc: "1개에서 10개까지 지원합니다. 여러 파일일 경우 1대다 흐름으로 처리합니다.",
      warnings: {
        missingA: "먼저 원본 문서 A를 선택하세요.",
        missingB: "최소 1개의 비교 문서 B를 선택하세요.",
        exceedB: "B 문서는 최대 10개까지 선택할 수 있습니다.",
        unsupported: "{name} 형식은 지원되지 않습니다. DOCX 또는 텍스트 선택이 가능한 PDF를 업로드하세요.",
        createFailed: "작업 생성에 실패했습니다."
      }
    },
    uploadCard: {
      clear: "비우기",
      importPrimary: "메인 문서 가져오기",
      importBatch: "비교 문서 가져오기",
      replaceHint: "다시 드래그해 교체할 수 있으며 자동 업로드되지는 않습니다.",
      dropHint: "파일을 여기에 끌어오거나 클릭하여 선택하세요.",
      empty: "선택된 파일이 없습니다",
      selectedSingle: "{name}",
      selectedMulti: "{count}개 파일 선택됨"
    },
    seo: {
      keyPoints: "핵심 포인트",
      insight: "인사이트",
      workflow: "워크플로",
      faq: "FAQ",
      related: "관련 페이지",
      viewPage: "페이지 보기"
    },
    stepper: {
      progress: "진행 상황"
    }
  },
  fr: {
    app: {
      defaultSiteTitle: "Contrôle de similarité des dossiers d'appel d'offres",
      defaultHomeTags: ["Sans connexion", "Aperçu gratuit", "Pages illimitées", "Taille illimitée", "Prêt à l'emploi"].join("|")
    },
    shell: {
      systemNotice: "Annonce système",
      language: "Langue",
      version: "Version",
      menu: {
        home: "Accueil",
        upload: "Téléverser",
        free: "Vérification gratuite",
        check: "Revue d'offre",
        compliance: "Conformité",
        docs: "Documentation"
      },
      step: {
        upload: "Espace d'envoi",
        uploadSub: "Soumettre les fichiers",
        processing: "Analyse IA",
        processingSub: "Comparaison en cours",
        results: "Résultats",
        resultsSub: "Voir le classement",
        compare: "Preuves",
        compareSub: "Comparer les originaux"
      },
      email: {
        eyebrow: "E-mail support",
        desc: "Idéal pour envoyer des captures, des besoins détaillés et des informations de liaison"
      },
      qrFallback: "Image indisponible"
    },
    upload: {
      title: "Espace de création de tâche",
      subtitle: "Téléversez l'offre principale A et l'offre de comparaison B pour lancer l'analyse de similarité.",
      recover: "Récupérer une tâche passée",
      keywordLabel: "Vérification par mots-clés",
      keywordPlaceholder: "Saisissez un mot-clé puis appuyez sur Entrée pour l'ajouter (ex. collusion, autorisation exclusive)",
      start: "Lancer l'analyse IA",
      recoverDialogTitle: "Récupérer le résultat",
      recoverTip: "Saisissez l'identifiant de tâche commençant par T",
      recoverPlaceholder: "Exemple : T20260626xxxx",
      cancel: "Annuler",
      recoverNow: "Récupérer",
      aTitle: "Offre principale A",
      aDesc: "Téléversez de préférence la version finale. Un seul fichier est autorisé.",
      bTitle: "Offre de comparaison B",
      bDesc: "Prend en charge 1 à 10 fichiers. Au-delà d'un fichier, un flux un-vers-plusieurs est utilisé.",
      warnings: {
        missingA: "Veuillez d'abord sélectionner l'offre principale A.",
        missingB: "Veuillez sélectionner au moins une offre B.",
        exceedB: "Vous pouvez sélectionner au maximum 10 fichiers B.",
        unsupported: "{name} n'est pas pris en charge. Veuillez téléverser un DOCX ou un PDF avec texte sélectionnable.",
        createFailed: "Échec de la création de la tâche."
      }
    },
    uploadCard: {
      clear: "Effacer",
      importPrimary: "Importer le document principal",
      importBatch: "Importer les documents de comparaison",
      replaceHint: "Vous pouvez encore glisser des fichiers pour les remplacer. Aucun envoi automatique.",
      dropHint: "Glissez les fichiers ici ou cliquez pour les sélectionner.",
      empty: "Aucun fichier sélectionné",
      selectedSingle: "{name}",
      selectedMulti: "{count} fichiers sélectionnés"
    },
    seo: {
      keyPoints: "Points clés",
      insight: "Analyse",
      workflow: "Processus",
      faq: "FAQ",
      related: "Liens associés",
      viewPage: "Voir la page"
    },
    stepper: {
      progress: "Progression"
    }
  },
  de: {
    app: {
      defaultSiteTitle: "Ausschreibungs-Similaritätsprüfung",
      defaultHomeTags: ["Ohne Login", "Kostenlose Vorschau", "Unbegrenzte Seiten", "Unbegrenzte Größe", "Sofort einsatzbereit"].join("|")
    },
    shell: {
      systemNotice: "Systemhinweis",
      language: "Sprache",
      version: "Version",
      menu: {
        home: "Start",
        upload: "Hochladen",
        free: "Kostenlos prüfen",
        check: "Angebotsprüfung",
        compliance: "Compliance",
        docs: "Dokumente"
      },
      step: {
        upload: "Upload-Bereich",
        uploadSub: "Dateien übermitteln",
        processing: "KI-Prüfung",
        processingSub: "Vergleich läuft",
        results: "Ergebnisse",
        resultsSub: "Ranking ansehen",
        compare: "Belege",
        compareSub: "Originale vergleichen"
      },
      email: {
        eyebrow: "Support-E-Mail",
        desc: "Geeignet für Screenshots, Problembeschreibungen und Integrationsinformationen"
      },
      qrFallback: "Bild nicht verfügbar"
    },
    upload: {
      title: "Arbeitsbereich zur Aufgabenerstellung",
      subtitle: "Laden Sie Hauptangebot A und Vergleichsangebot B hoch, um die Ähnlichkeitsprüfung zu starten.",
      recover: "Vorherige Aufgabe wiederherstellen",
      keywordLabel: "Stichwortprüfung",
      keywordPlaceholder: "Geben Sie ein Stichwort ein und drücken Sie Enter, um es hinzuzufügen (z. B. Absprache, Exklusivfreigabe)",
      start: "KI-Prüfung starten",
      recoverDialogTitle: "Prüfergebnis wiederherstellen",
      recoverTip: "Geben Sie die mit T beginnende Aufgaben-ID ein",
      recoverPlaceholder: "Beispiel: T20260626xxxx",
      cancel: "Abbrechen",
      recoverNow: "Jetzt wiederherstellen",
      aTitle: "Hauptangebot A",
      aDesc: "Bitte möglichst die finale Version hochladen. Es ist nur eine Datei erlaubt.",
      bTitle: "Vergleichsangebot B",
      bDesc: "Unterstützt 1 bis 10 Dateien. Bei mehreren Dateien wird ein Eins-zu-Viele-Ablauf verwendet.",
      warnings: {
        missingA: "Bitte wählen Sie zuerst Hauptangebot A aus.",
        missingB: "Bitte wählen Sie mindestens ein Vergleichsangebot B aus.",
        exceedB: "Maximal 10 B-Dateien können ausgewählt werden.",
        unsupported: "{name} wird nicht unterstützt. Bitte laden Sie DOCX oder ein PDF mit auswählbarem Text hoch.",
        createFailed: "Aufgabe konnte nicht erstellt werden."
      }
    },
    uploadCard: {
      clear: "Leeren",
      importPrimary: "Hauptdokument importieren",
      importBatch: "Vergleichsdokumente importieren",
      replaceHint: "Sie können weitere Dateien hineinziehen, um sie zu ersetzen. Kein automatischer Upload.",
      dropHint: "Dateien hierher ziehen oder klicken, um Dateien auszuwählen.",
      empty: "Noch keine Datei ausgewählt",
      selectedSingle: "{name}",
      selectedMulti: "{count} Dateien ausgewählt"
    },
    seo: {
      keyPoints: "Wichtige Punkte",
      insight: "Einordnung",
      workflow: "Ablauf",
      faq: "FAQ",
      related: "Verwandte Seiten",
      viewPage: "Seite ansehen"
    },
    stepper: {
      progress: "Fortschritt"
    }
  }
};

const baseExactTextTranslations: Partial<Record<AppLocale, Record<string, string>>> = {
  en: {
    "标书查重系统": "Bid Similarity Check",
    "无需登陆": "No Login",
    "基础免费": "Free Preview",
    "不限页数": "Unlimited Pages",
    "不限大小": "Unlimited Size",
    "开箱即用": "Ready to Use",
    "标书查重与投标文件风险检查平台": "Bid Similarity and Tender Risk Review Platform",
    "面向工程企业和乙方销售/商务团队，支持标书查重、标书检查、围标风险排查、关键字命中与原文证据复核。先上传文档获得结果预览，再按需进入深度比对与支付解锁。":
      "Designed for engineering firms and business teams, this site supports bid similarity checks, tender review, collusion-risk screening, keyword hits and original evidence review. Upload files first, preview the result, then unlock deeper comparison when needed.",
    "支持 DOCX / PDF": "Supports DOCX / PDF",
    "多文档 1 对多": "One-to-many comparison",
    "基础免费预览": "Free preview",
    "任务号 7 天找回": "7-day task recovery",
    "立即开始查重": "Start Checking Now",
    "查看使用文档": "View Guide",
    "系统能帮助你检查什么": "What the platform helps you inspect",
    "为什么这个站点更适合标书场景": "Why this site fits bid review scenarios better",
    "适合哪些团队使用": "Who should use it",
    "如何完成一次标书查重": "How to complete one bid similarity check",
    "首页常见问题": "Homepage FAQ",
    "继续浏览相关页面": "Explore related pages"
  },
  "zh-TW": {
    "标书查重系统": "標書查重系統",
    "无需登陆": "無需登入",
    "基础免费": "基礎免費",
    "不限页数": "不限頁數",
    "不限大小": "不限大小",
    "开箱即用": "開箱即用",
    "标书查重与投标文件风险检查平台": "標書查重與投標文件風險檢查平台",
    "支持 DOCX / PDF": "支援 DOCX / PDF",
    "多文档 1 对多": "多文件 1 對多",
    "基础免费预览": "基礎免費預覽",
    "任务号 7 天找回": "任務號 7 天找回",
    "立即开始查重": "立即開始查重",
    "查看使用文档": "查看使用文件",
    "系统能帮助你检查什么": "系統能幫助你檢查什麼",
    "为什么这个站点更适合标书场景": "為什麼這個站點更適合標書場景",
    "适合哪些团队使用": "適合哪些團隊使用",
    "如何完成一次标书查重": "如何完成一次標書查重",
    "首页常见问题": "首頁常見問題",
    "继续浏览相关页面": "繼續瀏覽相關頁面"
  },
  ja: {
    "标书查重系统": "入札書類重複チェック",
    "立即开始查重": "チェックを開始",
    "查看使用文档": "使い方を見る"
  },
  ko: {
    "标书查重系统": "입찰 문서 유사도 검사",
    "立即开始查重": "검사 시작",
    "查看使用文档": "사용 가이드 보기"
  },
  fr: {
    "标书查重系统": "Contrôle de similarité des dossiers d'appel d'offres",
    "立即开始查重": "Commencer l'analyse",
    "查看使用文档": "Voir le guide"
  },
  de: {
    "标书查重系统": "Ausschreibungs-Similaritätsprüfung",
    "立即开始查重": "Prüfung starten",
    "查看使用文档": "Anleitung ansehen"
  }
};

const exactTextTranslations: Partial<Record<AppLocale, Record<string, string>>> = (Object.keys(
  baseExactTextTranslations
) as AppLocale[]).reduce((acc, localeKey) => {
  acc[localeKey] = {
    ...(baseExactTextTranslations[localeKey] ?? {}),
    ...(extraExactTextTranslations[localeKey as keyof typeof extraExactTextTranslations] ?? {})
  };
  return acc;
}, {} as Partial<Record<AppLocale, Record<string, string>>>);

const localeState = ref<AppLocale>("zh-CN");

function normalizeLocale(input?: string | null): AppLocale {
  if (!input) {
    return "zh-CN";
  }

  const value = input.toLowerCase();
  if (value.startsWith("zh-tw") || value.startsWith("zh-hk") || value.startsWith("zh-mo")) {
    return "zh-TW";
  }
  if (value.startsWith("zh")) {
    return "zh-CN";
  }
  if (value.startsWith("ja")) {
    return "ja";
  }
  if (value.startsWith("ko")) {
    return "ko";
  }
  if (value.startsWith("fr")) {
    return "fr";
  }
  if (value.startsWith("de")) {
    return "de";
  }
  return "en";
}

function getByPath(source: MessageTree, path: string) {
  return path.split(".").reduce<string | MessageTree | undefined>((current, segment) => {
    if (!current || typeof current === "string") {
      return current;
    }
    return current[segment];
  }, source);
}

function interpolate(template: string, params?: Record<string, string | number>) {
  if (!params) {
    return template;
  }

  return template.replace(/\{(\w+)\}/g, (_, key) => String(params[key] ?? ""));
}

export function initAppLocale() {
  if (typeof window === "undefined") {
    return;
  }

  const storedLocale = window.localStorage.getItem(LOCALE_STORAGE_KEY);
  localeState.value = normalizeLocale(storedLocale || window.navigator.language);
  document.documentElement.lang = localeState.value;
}

export function setAppLocale(nextLocale: AppLocale) {
  localeState.value = normalizeLocale(nextLocale);
  if (typeof window !== "undefined") {
    window.localStorage.setItem(LOCALE_STORAGE_KEY, localeState.value);
    document.documentElement.lang = localeState.value;
  }
}

export function translateText(sourceText: string) {
  if (!sourceText) {
    return sourceText;
  }

  if (localeState.value === "zh-CN") {
    return sourceText;
  }

  const localeMap = exactTextTranslations[localeState.value];
  const englishMap = exactTextTranslations.en;
  return localeMap?.[sourceText] ?? englishMap?.[sourceText] ?? sourceText;
}

export function localizeDeep<T>(value: T): T {
  if (typeof value === "string") {
    return translateText(value) as T;
  }

  if (Array.isArray(value)) {
    return value.map((item) => localizeDeep(item)) as T;
  }

  if (value && typeof value === "object") {
    const result: Record<string, unknown> = {};
    for (const [key, item] of Object.entries(value as Record<string, unknown>)) {
      result[key] = localizeDeep(item);
    }
    return result as T;
  }

  return value;
}

export function useAppI18n() {
  const locale = computed(() => localeState.value);
  const elementPlusLocale = computed(() => elementPlusLocales[localeState.value]);
  const defaultHomeTags = computed(() => {
    const serialized = (getByPath(keyMessages[localeState.value], "app.defaultHomeTags") ??
      getByPath(keyMessages["zh-CN"], "app.defaultHomeTags") ??
      "") as string;
    return serialized.split("|").filter(Boolean);
  });

  function t(path: string, params?: Record<string, string | number>) {
    const localized =
      getByPath(keyMessages[localeState.value], path) ??
      getByPath(keyMessages.en, path) ??
      getByPath(keyMessages["zh-CN"], path);

    if (typeof localized === "string") {
      return interpolate(localized, params);
    }

    return path;
  }

  return {
    locale,
    localeOptions,
    elementPlusLocale,
    defaultHomeTags,
    setLocale: setAppLocale,
    t,
    translateText,
    localizeDeep
  };
}
